# Numpy - numerical python 

In [1]:
import numpy as np 

In [7]:
#1d array
arr0 = np.array([12,13])
print(arr0)
print(arr0.ndim)

[12 13]
1


In [6]:
#0 dimension array or scaler array a single element arry would be 0 d array like np.arr0(12)

In [11]:
# 2_D array = multiple 1d array clubbed together 
arr2= np. array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [12]:
# 3_D array = multiple 1d array clubbed together
arr3= np. array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.ndim) #for getting dimesion 
print(arr3.shape) #no of rows,coloum 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [17]:
#Create a numpy array with numpy.array module and with a data type integer and float.
arrint = np.array([1,2,3])
print(arrint)
print(arrint.dtype)
arrf = np.array([1.0,2.5,3.3])
print(arrf)
print(arrf.dtype)

[1 2 3]
int32
[1.  2.5 3.3]
float64


In [19]:
#coverting dtype
arrint = np.array([1,2,3], dtype= float)
print(arrint)
print(arrint.dtype)

[1. 2. 3.]
float64


In [20]:
#Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
#Also, print the shape and dimensions of the numpy arrays created above.

#1d array
arr1 = np.array([12,13])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

# 2_D array 
arr2= np. array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

# 3_D array 
arr3= np. array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.ndim)  
print(arr3.shape)

# 4_D array 
arr4= np. array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(arr4)
print(arr4.ndim)  
print(arr4.shape)

[12 13]
1
(2,)
[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
4
(1, 1, 4, 3)


In [22]:
#Create a 2x2, 3x3, and 4x4 identity matrix using numpy(identity matrix is square matrix row=coloumn, principla diagonalvalues should be 1)
#mannualy creating
arr2= np. array([[1,1,3],[4,1,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

arr3= np. array([[[1,1,3],[4,1,6],[7,8,1]]])
print(arr3)
print(arr3.ndim)  
print(arr3.shape)

[[1 1 3]
 [4 1 6]]
2
(2, 3)
[[[1 1 3]
  [4 1 6]
  [7 8 1]]]
3
(1, 3, 3)


In [25]:
#Create a 2x2, 3x3, and 4x4 identity matrix using numpy(identity matrix is square matrix row=coloumn, principla diagonalvalues should be 1)
# using numpy funcion

id2 = np.identity(2, dtype=int)
print(id2)

id3 = np.identity(3, dtype=int)
print(id3)

id4 = np.identity(4, dtype=int)
print(id4)


[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [32]:
#Create a numpy array with shape 2x5 that has all the elements as zero.
zero = np.zeros([2,5], dtype=int)
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [33]:
#Create a numpy array that has the shape 3x5 and all the elements are 5.
f= np.full([3,5],5)
print(f)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [37]:
#Create a numpy array with random integers in the range 0-100, and the sample size
#should be 25.
x = np.random.randint(0,100,25)
print(x)


[74 51 44 28 83 77 65 31 42 94 23 51 39 96 96 65 47 97 66 15 12 27 13 43
 94]


In [40]:
#Create a numpy array with a shape 3x3 that has all elements as 1.
one = np.ones([3,3], dtype=int)
print(one)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [44]:
#Create a numpy array in the shape 2x3 with random integers in the range 0-100.
#Reshape the array in the shape 3x2 and print the updated shape of the resultant array
arr= np.random.randint(0,100,(2,3))
print(arr)
arr.reshape(3,2)


[[76 88 20]
 [68 52 42]]


array([[76, 88],
       [20, 68],
       [52, 42]])

In [52]:
#Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the
#following operations on the same.
# Print the first ten elements of the array.
#Print the last ten elements of the array
#Print the elements from the indexes 10-25
#Print the element at the index 22
#Print the array using negative indexing.
#Print the last ten elements of the array, using negative indexing.

x = np.random.randint(0,1000,50)
print(x)
# Print the first ten elements of the array.(slicing)
x[0:10]
#Print the last ten elements of the array
x[40:49]
#Print the elements from the indexes 10-25
x[10:26]
#Print the element at the index 22
x[22]
#Print the array using negative indexing.
x[::-1]
#Print the last ten elements of the array, using negative indexing.
x[-10:]

[520 289 569 402 626 549 684 405 762 724 756 219  83 974 795 446 789  94
  28 254 409 429 450 968 890 726 506 310 902  63 288 626  30 121 214 478
 709 503 789 761 579 384 561 693 295 273 673 676  78  96]


array([579, 384, 561, 693, 295, 273, 673, 676,  78,  96])

In [67]:
#Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
#a. Insert the element 6 at the end of the array.
#b. Insert the element 10 at the beginning of the array.
#c. Insert the element 30, before 4.
#d. Update the element 5 as 50.
#e. Delete the element 50 in the updated array.
#f. Create a function to search for the element 30.
#g. Sort the array in ascending order

a= np.array([1,2,3,4,5])
print(a)

#a. Insert the element 6 at the end of the array.
a=np.append(a,6)
print(a)

#b. Insert the element 10 at the beginning of the array.
a= np.insert(a,0,10)#0 is the index of first element
print(a)

#c. Insert the element 30, before 4.
a= np.insert(a,4,30)
print(a)

#d. Update the element 5 as 50.
a[6]= 50
print(a)

#e. Delete the element 50 in the updated array.
a= np.delete(a,6)
print(a)

#f. Create a function to search for the element 30.
def search(arr,key):
    if key in arr:
        print("element is found")
    else:
        print("element is not found")
    
search(arr,30)

#g. Sort the array in ascending order

a.sort() #by default it will sort into ascending anf for decending we dont have function so we sort in asc and then reverse the array 
a


[1 2 3 4 5]
[1 2 3 4 5 6]
[10  1  2  3  4  5  6]
[10  1  2  3 30  4  5  6]
[10  1  2  3 30  4 50  6]
[10  1  2  3 30  4  6]
element is not found


array([ 1,  2,  3,  4,  6, 10, 30])